name: conedec
version: '0.1.0'
author: Christian Gram Kalhauge
maintainer: "Christian Gram Kalhauge <chrg@dtu.dk>"
synopsis: A cone based codec implementation
license: BSD3
license-file: LICENSE
# category: missing
# github: tbd

description: |
  A cone based codec implementation

ghc-options: 
- -Wall

extra-source-files:
  - LICENSE
  - package.yaml

dependencies:
  - base >= 4.10 && < 4.18
  - cones
  - aeson
  - scientific
  - vector
  - text
  - barbies
  - prettyprinter

library:
  source-dirs: src

tests:
  conedec-test:
    source-dirs: test
    main: Main.hs
    dependencies: 
      - conedec
      - bytestring
