name: cones
version: '0.1.0'
author: Christian Gram Kalhauge
maintainer: "Christian Gram Kalhauge <chrg@dtu.dk>"
synopsis: A library for defining cones.
license: BSD3
license-file: LICENSE
# category: missing
# github: tbd

description: |
  A library for defining cones.

ghc-options: 
- -Wall

extra-source-files:
  - package.yaml
  - LICENSE

dependencies:
  - base >= 4.10 && < 4.19
  - barbies
  - template-haskell

library:
  source-dirs: src

tests:
  cones-test:
    source-dirs: test
    main: Main.hs
    dependencies: 
      - cones

